spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/blog?useUnicode=true&characterEncoding=utf-8
    username: root
    password: 12112008Yt.

  jpa:
    hibernate:
      ddl-auto: update

logging:
  level:
    root: info
    com.princeoo: debug
  file:
    name: log/blog-pro.log

server:
  port: 80
